feat(compe): implement nvim-compe integration
wellle/tmux-complete.vim pull request #90
Opened 2021-02-12 16:14 UTC by rainerborene

It works amazingly well.

2021-03-15 13:42 UTC, kabouzeid requested changes

2021-03-15 13:42 UTC, kabouzeid commented on lua/compe_tmux/init.lua
> +  context.callback({ items = items })
Replace with
```lua
    vim.fn["tmuxcomplete#async#gather_candidates"](function (items)
      context.callback({ items = items })
    end)
```
for async completion.

2021-03-15 15:45 UTC, rainerborene commented on lua/compe_tmux/init.lua
> +  context.callback({ items = items })
Done. Thanks!

2021-03-25 10:43 UTC, kabouzeid commented
Hi @wellle, could you merge this? It's a small addition. I reviewed and tested the code, everything works as intended :)

2021-03-26 15:10 UTC, merged

2021-03-26 15:10 UTC, wellle commented
Hey thank you @rainerborene and @kabouzeid for this. And sorry for the delay!